variant: fcos
version: 1.5.0
passwd:
  users:
    - name: root
      groups:
        - root
      ssh_authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDFPly2MYEeh4FtFtftOa0qasGW4VNIzYv/ZzheQ/dFs martin@fedora
systemd:
  units:
    - name: docker.service
      mask: true

    - name: telegraf.service
      contents: |
        [Unit]
        Description=The plugin-driven server agent for reporting metrics into InfluxDB
        Documentation=https://github.com/influxdata/telegraf
        After=network.target

        [Service]
        Type=simple
        ExecStart=/bin/bash /usr/local/bin/run-telegraf
        Restart=on-failure
        StandardOutput=syslog
        StandardError=syslog

        [Install]
        WantedBy=multi-user.target

    - name: rotate-token.service
      contents: |
        [Unit]
        Description=Rotate token from bao

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/bin/bash -c '/usr/bin/podman run -e BAO_ADDR=https://openbao.hnatekmar.xyz -e VAULT_TOKEN=$(cat /root/.vault-token) -ti quay.io/openbao/openbao token renew'


    - name: rotate-token.timer
      enabled: true
      contents: |
        [Unit]
        Description=Run rotate-token.service every minute
        
        [Timer]
        OnCalendar=*:0/30
        
        [Install]
        WantedBy=multi-user.target

    - name: rpm-ostree-install-base.service
      enabled: true
      contents: |
        [Unit]
        Description=Layer vim with rpm-ostree
        Wants=network-online.target
        After=network-online.target

        # We run before `zincati.service` to avoid conflicting rpm-ostree
        # transactions.
        Before=zincati.service
        ConditionPathExists=!/var/lib/%N.stamp

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        # `--allow-inactive` ensures that rpm-ostree does not return an error
        # if the package is already installed. This is useful if the package is
        # added to the root image in a future Fedora CoreOS release as it will
        # prevent the service from failing.
        ExecStart=/usr/bin/rpm-ostree install --allow-inactive -y vim telegraf
        ExecStart=/bin/touch /var/lib/%N.stamp
        ExecStart=/bin/systemctl --no-block reboot

        [Install]
        WantedBy=multi-user.target

    - name: containerd.service
      enabled: true
      dropins:
        - name: 99-proxy.conf
          contents: |
            [Service]
            EnvironmentFile=/etc/proxy.env
storage:
  directories:
    - path: /etc/ucore-autorebase
      mode: 0754
  links:
    - path: /etc/localtime
      target: ../usr/share/zoneinfo/Europe/Prague
  files:
    - path: /usr/local/bin/run-telegraf
      mode: 0755
      contents:
        inline: |
          #!/bin/bash
          
          export INFLUX_TOKEN=$(/usr/bin/podman run -e BAO_ADDR=https://openbao.hnatekmar.xyz -e VAULT_TOKEN=$(cat /root/.vault-token) -ti quay.io/openbao/openbao kv get -field=influx_token secret/servers/common)
          exec /usr/bin/telegraf --config /etc/telegraf/custom-telegraf.conf

    - path: /etc/telegraf/custom-telegraf.conf
      mode: 0644
      contents:
        inline: |
          [agent]
            interval = "10s"
            metric_batch_size = 1000
          [[inputs.cpu]]
          [[inputs.disk]]
          [[inputs.diskio]]
          [[inputs.mem]]
          [[inputs.processes]]
          [[inputs.system]]
          [[outputs.influxdb_v2]]
          urls = ["https://influx.hnatekmar.xyz"]

    - path: /etc/containers/registries.conf.d/mirrors.conf
      mode: 0644
      contents:
        inline: |
          [[registry]]
          location="mirror-docker-io.hnatekmar.xyz"
          prefix="docker.io"

          [[registry]]
          location="mirror-gcr-io.hnatekmar.xyz"
          prefix="gcr.io"

          [[registry]]
          location="mirror-ghcr-io.hnatekmar.xyz"
          prefix="ghcr.io"

          [[registry]]
          location="mirror-quay-io.hnatekmar.xyz"
          prefix="quay.io"

    - path: /etc/yum.repos.d/telegraf.repo
      mode: 0755
      contents:
        inline: |
          [influxdata]
          name = InfluxData Repository - Stable
          baseurl = https://repos.influxdata.com/stable/x86_64/main
          enabled = 1
          gpgcheck = 1
          gpgkey = https://repos.influxdata.com/influxdata-archive_compat.key
    - path: /etc/profile.d/zz-defaults.sh
      contents:
        inline: |
          export EDITOR=vim
    - path: /etc/profile.d/zz-openbao.sh
      mode: 0755
      contents:
        inline: |-
          export VAULT_ADDR=https://openbao.hnatekmar.xyz
          export BAO_ADDR=https://openbao.hnatekmar.xyz
    - path: /etc/proxy.env
      mode: 0644
      contents:
        inline: |-
          http_proxy="http://172.16.100.61:3128"