variant: fcos
version: 1.5.0
passwd:
  users:
    - name: core
      groups:
        - root
      ssh_authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDFPly2MYEeh4FtFtftOa0qasGW4VNIzYv/ZzheQ/dFs martin@fedora
systemd:
  units:
    - name: docker.service
      mask: true

    - name: install-distrobox.service
      enabled: true
      contents: |
        [Unit]
        Description=Install Distrobox
        After=network-online.target

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/bash -c "curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh"
        RemainAfterExit=yes

        [Install]
        WantedBy=multi-user.target

    - name: serial-getty@ttyS0.service
      dropins:
        - name: autologin-core.conf
          contents: |
            [Service]
            # Override Execstart in main unit
            ExecStart=
            # Add new Execstart with `-` prefix to ignore failure`
            ExecStart=-/usr/sbin/agetty --autologin core --noclear %I $TERM
    - name: containerd.service
      enabled: true
      dropins:
        - name: 99-proxy.conf
          contents: |
            [Service]
            EnvironmentFile=/etc/proxy.env
storage:
  links:
    - path: /etc/localtime
      target: ../usr/share/zoneinfo/Europe/Prague
  files:
    - path: /etc/proxy.env
      mode: 0644
      contents:
        inline: |-
          http_proxy="http://172.16.100.61:3128"