name: Build Image using Container
on:
  push:

jobs:
  build:
    name: Build image
    runs-on: dind
    steps:
    - uses: actions/checkout@v4.2.2
    - name: remove all docker images
      run: docker rmi $(docker image ls -aq) --force
    - uses: docker/login-action@v3
      with:
        registry: gitea.hnatekmar.xyz
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        docker system prune --all
        docker build . -f caddy.Dockerfile -t gitea.hnatekmar.xyz/public/caddy:latest
        docker push --all-tags gitea.hnatekmar.xyz/public/caddy
